name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        uses: nbrg/huggingface-sync-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          huggingface_token: ${{ secrets.HF_TOKEN }}
          huggingface_repo: Wakaba0991/VK map
          repo_type: space
          space_sdk: streamlit
